services:
  sql:
    container_name: "sql2"
    image: mysql:9
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
volumes:
  mysql_db: